# This file was generated by GoReleaser. DO NOT EDIT.
cask "tlgme" do
  version "0.1.3"

  on_macos do
    on_arm do
      sha256 "6e75ac3efe963bf0796e807eda57b0e48e8ef40c760ae829a13435d74a29ec29"
      url "https://github.com/bettertomorrow-dev/tlgme/releases/download/v#{version}/tlgme_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "82a49e2afec38b5f9affff56e60fd5b8492fe5ac40e46237e74b238e7af94c24"
      url "https://github.com/bettertomorrow-dev/tlgme/releases/download/v#{version}/tlgme_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7f2311ad1890036b297ee54fd5ec75bb4ed1cb01514314c3fe3771a22d9b9d14"
      url "https://github.com/bettertomorrow-dev/tlgme/releases/download/v#{version}/tlgme_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f5cb1ac53f11e2e9b0d0f14e20644bf13dcd1d3c64c2ec7a4c24e7a2e0cd1f4c"
      url "https://github.com/bettertomorrow-dev/tlgme/releases/download/v#{version}/tlgme_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tlgme"
  desc "Send Telegram messages and wait for replies from the command line"
  homepage "https://github.com/bettertomorrow-dev/tlgme"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tlgme"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tlgme"]
    end
  end

  # No zap stanza required
end
