# This file was generated by GoReleaser. DO NOT EDIT.
cask "tlgme" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "d60798c98b57b73b2e39655b144a704b4e1e361bf1e69672d3ae8776957c145a"
      url "https://github.com/bettertomorrow-dev/tlgme/releases/download/v#{version}/tlgme_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3083c619a4f8143729f7822eafec70585f1dd880c6c4d823277e4baf1f8a6e1c"
      url "https://github.com/bettertomorrow-dev/tlgme/releases/download/v#{version}/tlgme_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "61e0b365b00d3714c38ef03b671d47c5842362ac09fdcc10dcf440b2392a59f6"
      url "https://github.com/bettertomorrow-dev/tlgme/releases/download/v#{version}/tlgme_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2dcfb3b49f9036ae9b72d88e262a91d91bdc6f7779d980d5beee8fcefcdff68c"
      url "https://github.com/bettertomorrow-dev/tlgme/releases/download/v#{version}/tlgme_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tlgme"
  desc "Send Telegram messages and wait for replies from the command line"
  homepage "https://github.com/bettertomorrow-dev/tlgme"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tlgme"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tlgme"]
    end
  end

  # No zap stanza required
end
