# This file was generated by GoReleaser. DO NOT EDIT.
cask "tlgme" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "8e45f550d6d7b0729c1b7ee89bdd21f954714a0c6b396671836c225dd49cab09"
      url "https://github.com/bettertomorrow-dev/tlgme/releases/download/v#{version}/tlgme_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c7767b9b3a6876d394ed65d4ebe8459e3ad9de49aa61fff8467e2daea7aaa042"
      url "https://github.com/bettertomorrow-dev/tlgme/releases/download/v#{version}/tlgme_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d24976e81d302353fd018f15aba56d789944291001b07ccf8e2aca22be84535d"
      url "https://github.com/bettertomorrow-dev/tlgme/releases/download/v#{version}/tlgme_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "29e6711b19bd86fb101f40f57b805e49a941ea844f9cf56296795b0ab3ad56c1"
      url "https://github.com/bettertomorrow-dev/tlgme/releases/download/v#{version}/tlgme_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tlgme"
  desc "Send Telegram messages and wait for replies from the command line"
  homepage "https://github.com/bettertomorrow-dev/tlgme"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tlgme"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tlgme"]
    end
  end

  # No zap stanza required
end
